apiVersion: v1
kind: Secret
metadata:
  name: gr-samples-mariadb-secret
type: Opaque
data:
  mariadb-root-password: MzBPQ2V2Ji8jfjFq
  mariadb-replication-username: cmVwbGljYXRpb25fdXNlcg==
  mariadb-replication-password: cmVwbGlQYTU1Lg==
