apiVersion: v1
kind: ConfigMap
metadata:
  name: gr-samples-mariadb-sql-configmap
data:
  primary.sql:  |
    CREATE USER IF NOT EXISTS '${DATABASE_REPLICATION_USER_USERNAME}'@'%'
      IDENTIFIED BY '${DATABASE_REPLICATION_USER_PASSWORD}';
    GRANT REPLICATION REPLICA ON *.* TO '${DATABASE_REPLICATION_USER_USERNAME}'@'%';
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

  replica.sql: |
    CHANGE MASTER TO
      MASTER_HOST='${STATEFULSET_NAME}-0.${SVC_NAME}.${NAMESPACE}.svc.cluster.local',
      MASTER_USER='${DATABASE_REPLICATION_USER_USERNAME}',
      MASTER_PASSWORD='${DATABASE_REPLICATION_USER_PASSWORD}',
      MASTER_USE_GTID = replica_pos,
      MASTER_CONNECT_RETRY=10;
